version: '3'

services:
  db:
      image: mariadb
      environment:
          MYSQL_USER: tester
          MYSQL_ROOT_PASSWORD: test123
          MYSQL_PASSWORD: test123
          MYSQL_DATABASE: magiclinkbot
      ports:
          - 3306:3306
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  adminer:
      image: adminer
      ports:
          - 8080:8080